/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cs;

import Conectar.Conectar;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author usuario
 */
public class RegistroComida extends javax.swing.JFrame {

    /**
     * Creates new form RegistroComida
     */

    DefaultTableModel modelo;
    public RegistroComida() {
        initComponents();
        actualizar();
    }
    
    private void llenarComboBox() {
        comboCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));
        try{
            PreparedStatement ps = null;
            ResultSet rs = null;
            Conectar conn = new Conectar();
            Connection con = conn.getConnection();
            
            String sql = "SELECT * FROM TIPO WHERE TIPEST = ?";
            ps = con.prepareStatement(sql);
            ps.setString(1, "Activo");
            rs = ps.executeQuery();
            while(rs.next()){
                comboCategoria.addItem(rs.getObject(2).toString());
            }
            conn.desconectar();
        }
        catch(SQLException ex){
            System.err.println(ex.toString());
        }
    }
    private void actualizar(){
        modelo=new DefaultTableModel();
        modelo.addColumn("Código");
        modelo.addColumn("Nombre");
        modelo.addColumn("Precio");
        modelo.addColumn("Descripción");
        modelo.addColumn("Categoría");
        modelo.addColumn("Estado");
        
        
        this.jTable1.setModel(modelo);
        this.setLocationRelativeTo(null);
        try{
            
            PreparedStatement ps = null;
            ResultSet rs = null;
            
            Conectar conn = new Conectar();
            Connection con = conn.getConnection();
            
            String sql = "SELECT * FROM COMIDA";
            
            ps = con.prepareStatement(sql);
            rs = ps.executeQuery();
            
            ResultSetMetaData rsMd = rs.getMetaData();
            int cantidadColumnas = rsMd.getColumnCount();
         
            
            while(rs.next()){
                Object[] filas = new Object[cantidadColumnas];
                for(int i = 0; i<cantidadColumnas; i++){
                    if(i!=4){
                        filas[i] = rs.getObject(i + 1);
                    }
                    else{
                        ResultSet rs2 = null;
                        sql = "SELECT TIPNOM FROM TIPO WHERE TIPCOD = ?";
                        ps = con.prepareStatement(sql);
                        ps.setString(1, rs.getObject(i+1).toString());
                        rs2 = ps.executeQuery();
                        rs2.next();
                        filas[i] = rs2.getObject(1);
                    }
                }
                modelo.addRow(filas);
                
                //jtEmpresaTransportista.setPreferredSize(new Dimension(240, jtEmpresaTransportista.getPreferredSize().height + 16));
            }
            
            conn.desconectar();
        }
        catch(SQLException ex){
            System.err.println(ex.toString());
        }
        llenarComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        txtPrecio = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        txtNombre = new javax.swing.JTextField();
        comboCategoria = new javax.swing.JComboBox();
        checkEstado = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(74, 4, 21));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setBackground(new java.awt.Color(204, 204, 204));
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 610, 160));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Código:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Registro de datos-\"COMIDA\"");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Precio :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, 50, -1));

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Nombre  :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, -1, -1));

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Categoria:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Estado    :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, -1, -1));

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Descripción:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 90, -1));

        txtCodigo.setBackground(new java.awt.Color(74, 4, 21));
        txtCodigo.setForeground(new java.awt.Color(255, 255, 255));
        txtCodigo.setBorder(null);
        jPanel1.add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 100, 20));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 110, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 90, 110, -1));

        txtPrecio.setBackground(new java.awt.Color(74, 4, 21));
        txtPrecio.setForeground(new java.awt.Color(255, 255, 255));
        txtPrecio.setBorder(null);
        jPanel1.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 70, 100, 20));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 110, -1));

        txtNombre.setBackground(new java.awt.Color(74, 4, 21));
        txtNombre.setForeground(new java.awt.Color(255, 255, 255));
        txtNombre.setBorder(null);
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, 100, 20));

        comboCategoria.setBackground(new java.awt.Color(74, 4, 21));
        comboCategoria.setForeground(new java.awt.Color(255, 255, 255));
        comboCategoria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Postre", "Bebida", "Comida" }));
        comboCategoria.setBorder(null);
        jPanel1.add(comboCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 70, 20));

        checkEstado.setBackground(new java.awt.Color(74, 4, 21));
        checkEstado.setForeground(new java.awt.Color(204, 204, 204));
        checkEstado.setText("Disponible");
        checkEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkEstadoActionPerformed(evt);
            }
        });
        jPanel1.add(checkEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, -1, -1));

        txtDescripcion.setBackground(new java.awt.Color(74, 4, 21));
        txtDescripcion.setColumns(10);
        txtDescripcion.setForeground(new java.awt.Color(255, 255, 255));
        txtDescripcion.setRows(5);
        txtDescripcion.setDisabledTextColor(new java.awt.Color(153, 153, 153));
        txtDescripcion.setMargin(new java.awt.Insets(1, 1, 1, 1));
        jScrollPane1.setViewportView(txtDescripcion);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 490, 40));

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\maxim\\Documents\\NetBeansProjects\\CS\\src\\imagen\\precio.png")); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, -1, 20));

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\maxim\\Documents\\NetBeansProjects\\CS\\src\\imagen\\estado.png")); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, -1, 20));

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\maxim\\Documents\\NetBeansProjects\\CS\\src\\imagen\\nombre.png")); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, -1, 20));

        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\maxim\\Documents\\NetBeansProjects\\CS\\src\\imagen\\codigo (1).png")); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, 20));

        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\maxim\\Documents\\NetBeansProjects\\CS\\src\\imagen\\cambiar.png")); // NOI18N
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, 20, 20));

        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Users\\maxim\\Documents\\NetBeansProjects\\CS\\src\\imagen\\categoria.png")); // NOI18N
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, 20));

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\maxim\\Documents\\NetBeansProjects\\CS\\src\\imagen\\mas.png")); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 20, 20));

        jLabel15.setBackground(new java.awt.Color(204, 204, 204));
        jLabel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 20, 20));

        jTable1.setBackground(new java.awt.Color(74, 4, 21));
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Nombre", "Precio", "Categoria", "Estado", "Descripcion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setSelectionBackground(new java.awt.Color(204, 204, 204));
        jTable1.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane2.setViewportView(jTable1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 590, 120));

        jLabel16.setBackground(new java.awt.Color(204, 204, 204));
        jLabel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 610, 170));

        jLabel17.setBackground(new java.awt.Color(204, 204, 204));
        jLabel17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 610, 50));

        jButton2.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 11)); // NOI18N
        jButton2.setText("GUARDAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, -1, 20));

        jButton3.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 11)); // NOI18N
        jButton3.setText("ELIMINAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 90, 20));

        jButton4.setFont(new java.awt.Font("Yu Gothic Light", 0, 11)); // NOI18N
        jButton4.setText("MODIFICAR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, -1, 20));

        jLabel18.setIcon(new javax.swing.ImageIcon("C:\\Users\\maxim\\Documents\\NetBeansProjects\\CS\\src\\imagen\\descripcion.png")); // NOI18N
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, 20));

        jLabel19.setIcon(new javax.swing.ImageIcon("C:\\Users\\maxim\\Documents\\NetBeansProjects\\CS\\src\\imagen\\guardar.png")); // NOI18N
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 20, 20));

        jLabel20.setIcon(new javax.swing.ImageIcon("C:\\Users\\maxim\\Documents\\NetBeansProjects\\CS\\src\\imagen\\eliminar.png")); // NOI18N
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 20, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkEstadoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Categoria categoria=new Categoria();
        categoria.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        try{
            PreparedStatement ps = null;
            Conectar conn = new Conectar();
            Connection con = conn.getConnection();
            ResultSet rs = null;
            String sql;
            boolean existe = false;
            sql = "SELECT * FROM COMIDA WHERE COMCOD = ?";
            ps = con.prepareStatement(sql);
            ps.setString(1, txtCodigo.getText());
            rs = ps.executeQuery();
            while(rs.next())
                existe = true;
            
            String estado;
            if(checkEstado.isSelected()){
                estado = "Activo";
            }
            else{
                estado = "Inactivo";
            }
            //****************************
            ResultSet rs2 = null;
            PreparedStatement ps2 = null;
            sql = "SELECT TIPCOD FROM TIPO WHERE TIPNOM = ?";
            ps2 = con.prepareStatement(sql);
            ps2.setString(1, comboCategoria.getSelectedItem().toString());
            rs2 = ps2.executeQuery();
            rs2.next();
            String tipo = rs2.getObject(1).toString();
            //****************************
            if(existe){
                sql = "UPDATE COMIDA SET COMNOM = ?, COMPRE = ?, COMDES = ?, COMTIPCOD = ?, COMEST = ? WHERE COMCOD = ?";
                ps = con.prepareStatement(sql);
                ps.setString(1, txtNombre.getText());
                ps.setString(2, txtPrecio.getText());
                ps.setString(3, txtDescripcion.getText());
                ps.setString(4, tipo);
                ps.setString(5, estado);
                ps.setString(6, txtCodigo.getText());
            }
            else{
                sql = "INSERT INTO COMIDA (COMCOD, COMNOM, COMPRE, COMDES, COMTIPCOD, COMEST) VALUES (?, ?, ?, ?, ?, ?)";
                ps = con.prepareStatement(sql);
                ps.setString(1, txtCodigo.getText());
                ps.setString(2, txtNombre.getText());
                ps.setString(3, txtPrecio.getText());
                ps.setString(4, txtDescripcion.getText());
                ps.setString(5, tipo);
                ps.setString(6, estado);
            }
            ps.executeUpdate();
            actualizar();
        }
        catch(SQLException ex){
            System.err.println(ex.toString());
        }
        txtCodigo.setText("");
        txtNombre.setText("");
        txtPrecio.setText("");
        txtDescripcion.setText("");
        checkEstado.setSelected(false);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        int fila = jTable1.getSelectedRow();
        String codigo = jTable1.getValueAt(fila, 0).toString();
        try{
            Conectar conn = new Conectar();
            Connection con = conn.getConnection();
            PreparedStatement ps = null;
            String sql = "UPDATE COMIDA SET COMEST = ? WHERE COMCOD = ?";
            ps = con.prepareStatement(sql);
            ps.setString(1, "Inactivo");
            ps.setString(2, codigo);
            ps.executeUpdate();
        }
        catch(SQLException ex){
            System.err.println(ex.toString());
        }
        actualizar();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int fila = jTable1.getSelectedRow();
        String codigo = jTable1.getValueAt(fila, 0).toString();
        String nombre = jTable1.getValueAt(fila, 1).toString();
        String precio = jTable1.getValueAt(fila, 2).toString();
        String descripcion;
        if(jTable1.getValueAt(fila, 3) != null){
            descripcion = jTable1.getValueAt(fila, 3).toString();
        }
        else{
            descripcion = "";
        }
        String categoria = jTable1.getValueAt(fila, 4).toString();
        String estado;
        if(jTable1.getValueAt(fila, 5) != null){
            estado = jTable1.getValueAt(fila, 5).toString();
        }
        else{
            estado = "";
        }
        
        txtCodigo.setText(codigo);
        txtNombre.setText(nombre);
        txtPrecio.setText(precio);
        if(estado.equals("Activo"))
            checkEstado.setSelected(true);
        else
            checkEstado.setSelected(false);
        comboCategoria.setSelectedItem(categoria);
        txtDescripcion.setText(descripcion);
       
       
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    
    public void setBox(JTable tabla,TableColumn columna){
        JComboBox c=new JComboBox();
        c.addItem("Postre");
        c.addItem("Bebidas");
        c.addItem("Comida");
        
        columna.setCellEditor(new DefaultCellEditor(c));
        DefaultTableCellRenderer renderer=new DefaultTableCellRenderer();
        renderer.setToolTipText("Selecione categoria");
        columna.setCellRenderer(renderer);
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroComida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroComida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroComida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroComida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroComida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox checkEstado;
    private javax.swing.JComboBox comboCategoria;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
